spring.application.name=transactions

#BD Credentials
spring.datasource.url=jdbc:postgresql://tenpo:5432/tenpo_db
spring.datasource.username=test
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# BD Config
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=GokuSSj2Mysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=3600000
jwt.refreshExpiration=2592000000